name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: 'Run Jdbc, Android, and Native-Linux Tests'
        if: matrix.os == 'ubuntu-latest'
        run: >-
          ./gradlew build --stacktrace
